### ISSUE TITLE
Look at Yarn 3

### ISSUE THREAD

**Issue by JSn1nj4** [JSn1nj4/ElliotDerhay.com#114]
Been on 1.x for a while.
- [Yarn article](https://yarnpkg.com/getting-started/install)
- [Heroku article](https://devcenter.heroku.com/articles/migrating-to-yarn-2)
- [Heroku: setting yarn berry version](https://devcenter.heroku.com/changelog-items/2538)

**Comment by zach2825** [comment]
Yarn 2 was never really released, and yarn 3 is basically broken. That's why no body uses it. the latest 1.22.x is acceptable..

**Comment by JSn1nj4** [comment]
Funny, I was just talking to a coworker about this: https://dev.to/corysimmons/comment/1j2g9

Not specifically about newer Yarn, but that some Node deps might explicitly reference the `node_modules/` folder. 😂

**Comment by JSn1nj4** [comment]
I think I am gonna try to switch after all, just to see what it's like myself. At least Berry has backwards compatibility support for `node_modules/`, so I'll just turn that on if I run into issues with that folder being hard-coded.
